version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/rails_docker2/src
    steps:
      - checkout:
        path: ~/rails-docker2
      - ruby/install-deps


workflows:
  version: 2
    build_and_test:
      jobs:
        - build
        - test:
          requires:
            - build